name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: testing

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            testing/package-lock.json
            frontend/package-lock.json

      - name: Install testing deps
        run: npm ci

      - name: Install frontend deps
        run: npm ci
        working-directory: ../frontend

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests (frontend only, localhost)
        run: npx playwright test --config=playwright.config.ts --reporter=html

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: testing/playwright-report/
          retention-days: 30
